apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-app
  template:
    metadata:
      labels:
        app: env-app
    spec:
      containers:
        - name: env-app
          image: lucasfernandesjo/env-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: env-secrets
